### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by lyusupov** [itay-grudev/twr-aprs#1]
https://github.com/erstec/APRS-ESP/discussions/29

**Comment by itay-grudev** [comment]
@lyusupov Thanks a lot. I am aware of your project, but couldn't get it to run in my boards and I spent a day trying.

I have a:

* T-TWR Rev 2
* T-TWR Rev 1.4
 
Maybe we can collaborate.

**Comment by itay-grudev** [comment]
@lyusupov Also Neither TWR board of mine has a DAC. How did you manage to synthesize AFSK?

**Comment by itay-grudev** [comment]
@lyusupov Oh! You answered this already in https://github.com/erstec/APRS-ESP/discussions/29. I'll take another go at it.

**Comment by lyusupov** [comment]
https://drive.google.com/file/d/18a2PpIE4KQ6lYPcmPZgXnCYFSRYEqKz-/view
